<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=9" >

<title>Genotype Identification with the Aid of Nile Blue A with a Mixed Population</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>





</head>

<body>
<h1>Genotype Identification with the Aid of Nile Blue A with a Mixed Population</h1>

<h2>11/22/2013 Tyler Shimko</h2>

<p>This experiment dealt with attempting to identify the genotype of the hermaphrodite which gave rise to a population of animals using Nile Blue A to aid in the identification of the sperm activation phenotype. Protocol was as follows:</p>

<ol>
<li>him-5 males crossed with him-5; me86 hermaphrodites</li>
<li>Cross progeny are heterozygous for the me86 allele, pick 15 hermaphrodites to individual plates and allow to grow up</li>
<li>In addition to the heterozygous animals, pick 15 animals from each of the parental strains to individual plates and allow them to grow up</li>
<li>Four days after picking the worms to individual plates, stain the animals by pipetting 120 µL 1:8 Nile Blue A solution on to the plate</li>
<li>Let the plates sit and stain overnight</li>
<li>Fives days after picking observe and score the animals</li>
</ol>

<h2>Scoring</h2>

<p>The table below shows the raw scoring data. </p>

<pre><code>##    Plate.Number Genotype.Guess Actual.Genotype Right.or.Wrong.                 Notes
## 1             1           me86            me86             1.0                      
## 2             2            Kh5             Kh5             1.0                      
## 3             3          cross           cross             1.0                      
## 4             4          cross             Kh5             0.0                      
## 5             5           me86            me86             1.0                      
## 6             6            Kh5           cross             0.0 Only 2 males on plate
## 7             7            Kh5           cross             0.0                      
## 8             8           me86            me86             1.0                      
## 9             9          cross             Kh5             0.0                      
## 10           10           me86            me86             1.0                      
## 11           11          cross           cross             1.0                      
## 12           12            Kh5            me86             0.0                      
## 13           13            Kh5           cross             0.0                      
## 14           14          cross           cross             1.0                      
## 15           15            Kh5             Kh5             1.0                      
## 16           16          cross             Kh5             0.0                      
## 17           17           me86            me86             1.0                      
## 18           18          cross           cross             1.0                      
## 19           19           me86            me86             1.0                      
## 20           20          cross           cross             1.0                      
## 21           21            Kh5             Kh5             1.0                      
## 22           22            Kh5             Kh5             1.0                      
## 23           23            Kh5             Kh5             1.0   No animals on plate
## 24           24           me86             Kh5             0.0                      
## 25           25          cross           cross             1.0                      
## 26           26           me86            me86             1.0                      
## 27           27          cross            me86             0.0                      
## 28           28           me86           cross             0.0                      
## 29           29           me86             Kh5             0.0                      
## 30           30            Kh5             Kh5             1.0                      
## 31           31            Kh5           cross             0.0                      
## 32           32          cross            me86             0.0                      
## 33           33            Kh5             Kh5             1.0                      
## 34           34           me86            me86             1.0                      
## 35           35           me86             Kh5             0.0                      
## 36           36           me86           cross             0.0                      
## 37           37          cross           cross             1.0                      
## 38           38            Kh5             Kh5             1.0                      
## 39           39          cross             Kh5             0.0                      
## 40           40           me86            me86             1.0                      
## 41           41            Kh5            me86             0.0                      
## 42           42           me86            me86             1.0                      
## 43           43          cross           cross             1.0                      
## 44           44          cross           cross             1.0                      
## 45           45           me86            me86             1.0                      
## 46           NA                                           28.0                    18
## 47           NA                                            0.6      0.62962962962963
</code></pre>

<h2>Analysis</h2>

<p>The table below shows the frequency with which plates were identified correctly or incorrectly. The rows indicate the genotype guess and the columns indicate the actual genotype.</p>

<pre><code>##        
##            cross Kh5 me86
##          2     0   0    0
##   cross  0     9   4    2
##   Kh5    0     4   8    2
##   me86   0     2   3   11
</code></pre>

<p>The plates arising from cross progeny (&ldquo;cross&rdquo; plates), were correctly identified 60% of the time. The Kh5 parental plates were correctly identified 57.14% of the time. The me86 parental plates were correctly identified 68.75% of the time.</p>

<p>The table below shows the frequency (as a percentage) with which each strain was identified, either correctly or incorrectly as the columnar strain.</p>

<pre><code>##        
##                 cross    Kh5   me86
##         100.00   0.00   0.00   0.00
##   cross   0.00  60.00  26.67  13.33
##   Kh5     0.00  28.57  57.14  14.29
##   me86    0.00  12.50  18.75  68.75
</code></pre>

<h2>Discussion</h2>

<p>As a result of this experiemnt, it is now clear that Nile Blue A does greatly aid in distinguishing the activated from the nonactivated phenotype. However, the level of error in identifying the genotype of the mixed strains means that this method needs to be refined before it can be implemented. For instance, Kh5 plates were only correctly identified 57.14% of the time. Since this is the phenotype that we would like to isolate during scoring in the future, the correct identification of these animals <em>must</em> improve. In addition the cross plates were misidentified as Kh5 26.67% of the time. This error rate will not work during the actual screen.</p>

</body>

</html>

